### ISSUE TITLE
error running generate_hdf5

### ISSUE THREAD

**Issue by xjoshramos** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#10]
('Image ID ', 90108)
('Image ID ', 179112)
('Image ID ', 311295)
('Num samples ', 55242)
Traceback (most recent call last):
  File "generate_hdf5.py", line 323, in <module>
    writeHDF5()
  File "generate_hdf5.py", line 220, in writeHDF5
    meta_data[clidx][i] = long(height_binary[i])
ValueError: invalid literal for long() with base 10: ''

**Comment by Marcovaldong** [comment]
@xjoshramos Hi, how did you get mask_miss and mask_all imgs? I want to transfer this model to a new dataset which has 14kepoints for a person, I need to generate mask_miss and mask_all images to retrain the model

**Comment by xjoshramos** [comment]
Generate_mask.py script in the training folder. Are you able to run the hdf5 script for preaparing the data?

**Comment by Marcovaldong** [comment]
I got the same error, and I don't understand what does the function float2bytes for.
I did ignore the generate_mask.py. Now I'm trying to transfer the model to a new dataset, and the annotation doesn't have segementation, do you know how should I deal with the mask_miss and mask_all matrix.

**Comment by Marcovaldong** [comment]
I got the same error, and I don't understand what does the function float2bytes for.
I did ignore the generate_mask.py. Now I'm trying to transfer the model to a new dataset, and the annotation doesn't have segmentation, do you know how should I deal with the mask_miss and mask_all matrix.

**Comment by michalfaber** [comment]
@xjoshramos This error occurs on python 2.x Try to tun the script under python 3.5

**Comment by xjoshramos** [comment]
![000000000139](https://user-images.githubusercontent.com/4721207/31844409-5f7d75fc-b5ad-11e7-9922-167b908d84ca.jpg)
![mask_all_000000000139](https://user-images.githubusercontent.com/4721207/31844416-65e51878-b5ad-11e7-9c50-00b008b1eee6.png)
![mask_miss_000000000139](https://user-images.githubusercontent.com/4721207/31844419-6859dab2-b5ad-11e7-8055-ae3f123d111c.png)

**Comment by xjoshramos** [comment]
mask_all, mask_miss
Its used in the loss function because not every person is annotated inside the coco set.

**Comment by GaogaoT** [comment]
Hi, I encountered an error while using Python3.5, I have passed the step 'python3 setup.py install' , but when I do 'from pycocotools.coco import COCO' ", the error '_mask.so: undefined symbol: _Py_ZeroStruct
' came out, would you like to help me solve the problem

**Comment by andrehuang** [comment]
Is it possible to fix the error:
`ValueError: invalid literal for long() with base 10: ''`
in Python2?

**Comment by anatolix** [comment]
@GaogaoT you have several pythons installed and they mixed libraries, use vitrualenv or conda and install/compile everything with one version of python

**Comment by kevinlin311tw** [comment]
@GaogaoT You may want to rebuild your coco api using python3.x
1. go to `coco/PythonAPI`
2. Setup your coco api using `sudo python3 setup.py build_ext --inplace` under `coco/PythonAPI`
3. Then, go back to the `training` folder and run `python3 generate_hdf5.py`

**Comment by GuruMulay** [comment]
@GaogaoT, I tried what @kevinlin311tw suggested above, but didn't work. So I did the setup again like
$ python setup.py install

**Comment by cchamber** [comment]
Tried running the script in python 2.7 and got the same error as @xjoshramos  :

('Image ID ', 90108)
('Image ID ', 179112)
('Image ID ', 311295)
('Num samples ', 55242)
Traceback (most recent call last):
File "generate_hdf5.py", line 323, in 
writeHDF5()
File "generate_hdf5.py", line 220, in writeHDF5
meta_data[clidx][i] = long(height_binary[i])
ValueError: invalid literal for long() with base 10: ''

Tried running in Python 3.5 from a virtual env. The code throws this error, same as @GaogaoT :

 File "generate_hdf5.py", line 4, in <module>
    from pycocotools.coco import COCO
  File "/opt/anaconda/miniconda2/envs/py35/lib/python3.5/site-packages/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/opt/anaconda/miniconda2/envs/py35/lib/python3.5/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ImportError: /opt/anaconda/miniconda2/envs/py35/lib/python3.5/site-packages/pycocotools/_mask.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

Did anyone solve this issue?

**Comment by abinjoabraham** [comment]
Tried running the script in python 3.5 and got the same error as @xjoshramos 
('Image ID ', 90108)
('Image ID ', 179112)
('Image ID ', 311295)
('Value of count:', 55242)
('Num samples ', 55242)
Traceback (most recent call last):
  File "/Users/abi/PycharmProjects/Pose estimation Keras/training/generate_hdf5.py", line 326, in <module>
    writeHDF5()
  File "/Users/abi/PycharmProjects/Pose estimation Keras/training/generate_hdf5.py", line 233, in writeHDF5
    meta_data[clidx][i] = height_binary[i]
ValueError: invalid literal for long() with base 10: ''

Process finished with exit code 1

I am trying hard to find a fix. Till now couldn't find any.
