### ISSUE TITLE
ConfigObj keyError: 'param'

### ISSUE THREAD

**Issue by cdebadri** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#101]
I'm getting a KeyError: 'param' when I execute demo_image.py

```
Using TensorFlow backend.
start processing...
Traceback (most recent call last):
  File "keras_Realtime_Multi-Person_Pose_Estimation/demo_image.py", line 255, in <module>
    params, model_params = config_reader()
  File "/content/keras_Realtime_Multi-Person_Pose_Estimation/config_reader.py", line 8, in config_reader
    param = config['param']
  File "/usr/local/lib/python3.6/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'param'
```
I've installed configobj on colab. what can be done to avoid it?

**Comment by esgnn** [comment]
Did you find how to fix it?

**Comment by 1209805200** [comment]
> Did you find how to fix it?
> Edit:
> I forgot to copy config

how to copy config?what do you mean?

**Comment by ruks001** [comment]
there is a text file named "config". you have to copy it to the project directory

**Comment by byzaagl** [comment]
> I'm getting a KeyError: 'param' when I execute demo_image.py
> 
> ```
> Using TensorFlow backend.
> start processing...
> Traceback (most recent call last):
>   File "keras_Realtime_Multi-Person_Pose_Estimation/demo_image.py", line 255, in <module>
>     params, model_params = config_reader()
>   File "/content/keras_Realtime_Multi-Person_Pose_Estimation/config_reader.py", line 8, in config_reader
>     param = config['param']
>   File "/usr/local/lib/python3.6/dist-packages/configobj.py", line 554, in __getitem__
>     val = dict.__getitem__(self, key)
> KeyError: 'param'
> ```
> 
> I've installed configobj on colab. what can be done to avoid it?

did you find any way to solve that issue?
