### ISSUE TITLE
import error in augmentors.py

### ISSUE THREAD

**Issue by anbilly19** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#121]
`Traceback (most recent call last):                                                                                                                                                             File "train_pose1.py", line 17, in <module>                                                                                                                                                    from training.dataset import get_dataflow, batch_dataflow                                                                                                                                  File "../training/dataset.py", line 11, in <module>                                                                                                                                            from training.augmentors import ScaleAug, RotateAug, CropAug, FlipAug, \                                                                                                                   File "../training/augmentors.py", line 6, in <module>                                                                                                                                          from tensorpack.dataflow.imgaug.geometry import WarpAffineTransform,TransformAugmentorBase                                                                                               ImportError: cannot import name TransformAugmentorBase  `

**Comment by michalfaber** [comment]
Yes, the code is not compatible with the latest version of tensorpack. Try to use tensorpack==0.9.0.1
Thanks for the info.

**Comment by anbilly19** [comment]
Thanks for the exact stable version i was unable to find the correct one. But now i'm seeing a ZeroDivision error in ScaleAug line 226. while the code proceeds to the first epoch it shows the same error and gets stuck midway. I'm not sure of the cause tho.
Should i start a new issue for this lemme know

**Comment by michalfaber** [comment]
Are you using the annotation file person_keypoints_train2017.json ? If not, there should be bbox element in your json file, something like "bbox": [x, y, w, h]

**Comment by anbilly19** [comment]
Yes I'm using the same one. Download from the coco website.

**Comment by Deeptanshu-sankhwar** [comment]
@anbilly19 try unzipping wget http://images.cocodataset.org/annotations/annotations_trainval2017.zip in folder annotations.
Worked for me !!
