### ISSUE TITLE
[ERROR IN TRAINING ]AttributeError: 'AugImgMetadata' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Halation666** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#136]
Hi,I'm new to learn Deep Learning.Some problems occured to me while traing.Can anybody tell me the reason or some ideas.Thanks a lot!!!!!!!!
I can run the demo_image.py successfully,so I want to continue to train the model by COCO dataset.
When i run train_pose.py,the command window will show 'Epoch1/20000' then no response.Above it,it shows an error:"**AttributeError: 'AugImgMetadata' object has no attribute 'shape'**"
I have no idea about it .The following is my error log.
If anyone has some ideas,please tell me !thx!
By the way.I'm Windows10+cuda8.0+cudnn6.0.21+tensorflow-gpu 1.3.0+keras2.0.7

**ERROR LOG:**

[0502 17:12:41 @parallel.py:207] WRN MultiProcessRunner does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
Using TensorFlow backend.
[0502 17:13:09 @develop.py:109] WRN [Deprecated] augment_return_params [<string>:1] will be deprecated after 06 Jun. Please use `get_transform` instead!
[0502 17:13:09 @argtools.py:138] WRN The old augmentor interface was deprecated. Please implement ScaleAug with `get_transform` instead!
Process _Worker-1:
Traceback (most recent call last):
  File "e:\anaconda3\envs\tfpose\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "e:\anaconda3\envs\tfpose\lib\site-packages\tensorpack\dataflow\parallel.py", line 192, in run
    for dp in self.ds:
  File "e:\anaconda3\envs\tfpose\lib\site-packages\tensorpack\dataflow\common.py", line 314, in __iter__
    for dp in self.ds:
  File "e:\anaconda3\envs\tfpose\lib\site-packages\tensorpack\dataflow\common.py", line 314, in __iter__
    for dp in self.ds:
  File "e:\anaconda3\envs\tfpose\lib\site-packages\tensorpack\dataflow\common.py", line 315, in __iter__
    ret = self.func(copy(dp))  # shallow copy the list
  File "..\training\dataset.py", line 100, in augment
    scale=meta.scale))
  File "e:\anaconda3\envs\tfpose\lib\site-packages\tensorpack\utils\develop.py", line 144, in new_func
    return func(*args, **kwargs)
  File "e:\anaconda3\envs\tfpose\lib\site-packages\tensorpack\dataflow\imgaug\base.py", line 208, in augment_return_params
    return t.apply_image(d), t
  File "e:\anaconda3\envs\tfpose\lib\site-packages\tensorpack\dataflow\imgaug\transform.py", line 119, in apply_image
    assert img.shape[:2] == (self.h, self.w)
AttributeError: 'AugImgMetadata' object has no attribute 'shape'
Epoch 1/2

**Comment by Secondgrade** [comment]
> Hi,I'm new to learn Deep Learning.Some problems occured to me while traing.Can anybody tell me the reason or some ideas.Thanks a lot!!!!!!!!
> I can run the demo_image.py successfully,so I want to continue to train the model by COCO dataset.
> When i run train_pose.py,the command window will show 'Epoch1/20000' then no response.Above it,it shows an error:"**AttributeError: 'AugImgMetadata' object has no attribute 'shape'**"
> I have no idea about it .The following is my error log.
> If anyone has some ideas,please tell me !thx!
> By the way.I'm Windows10+cuda8.0+cudnn6.0.21+tensorflow-gpu 1.3.0+keras2.0.7
> 
> **ERROR LOG:**
> 
> [0502 17:12:41 @parallel.py:207] WRN MultiProcessRunner does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
> Using TensorFlow backend.
> [0502 17:13:09 @develop.py:109] WRN [Deprecated] augment_return_params [:1] will be deprecated after 06 Jun. Please use `get_transform` instead!
> [0502 17:13:09 @argtools.py:138] WRN The old augmentor interface was deprecated. Please implement ScaleAug with `get_transform` instead!
> Process _Worker-1:
> Traceback (most recent call last):
> File "e:\anaconda3\envs\tfpose\lib\multiprocessing\process.py", line 249, in _bootstrap
> self.run()
> File "e:\anaconda3\envs\tfpose\lib\site-packages\tensorpack\dataflow\parallel.py", line 192, in run
> for dp in self.ds:
> File "e:\anaconda3\envs\tfpose\lib\site-packages\tensorpack\dataflow\common.py", line 314, in **iter**
> for dp in self.ds:
> File "e:\anaconda3\envs\tfpose\lib\site-packages\tensorpack\dataflow\common.py", line 314, in **iter**
> for dp in self.ds:
> File "e:\anaconda3\envs\tfpose\lib\site-packages\tensorpack\dataflow\common.py", line 315, in **iter**
> ret = self.func(copy(dp)) # shallow copy the list
> File "..\training\dataset.py", line 100, in augment
> scale=meta.scale))
> File "e:\anaconda3\envs\tfpose\lib\site-packages\tensorpack\utils\develop.py", line 144, in new_func
> return func(*args, **kwargs)
> File "e:\anaconda3\envs\tfpose\lib\site-packages\tensorpack\dataflow\imgaug\base.py", line 208, in augment_return_params
> return t.apply_image(d), t
> File "e:\anaconda3\envs\tfpose\lib\site-packages\tensorpack\dataflow\imgaug\transform.py", line 119, in apply_image
> assert img.shape[:2] == (self.h, self.w)
> AttributeError: 'AugImgMetadata' object has no attribute 'shape'
> Epoch 1/2

Hi，I'm using this project and get the same error. Have you solve this problem? I am developing my project on MAC. And I paste the errorReport  at the bottom.
    assert img.shape[:2] == (self.h, self.w)
AttributeError: 'AugImgMetadata' object has no attribute 'shape'
