### ISSUE TITLE
Error when checking input: expected input_2 to have shape (None, None, None, 30) but got array with shape (10, 46, 46, 38)

### ISSUE THREAD

**Issue by binliu-base** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#16]
I try to launch a training test with the following steps.

1. Start training data server in the first terminal session. ./rmpe_dataset_server ../../keras_Realtime_Multi-Person_Pose_Estimation/dataset/train_dataset.h5 5555

Total samples: 54942
Epoch 1
curr_sample/total_samples/curr_epoch = 1/54942/1

2. Start validation data server in a second terminal session. ./rmpe_dataset_server ../../keras_Realtime_Multi-Person_Pose_Estimation/dataset/val_dataset.h5 5556

Total samples: 300
Epoch 1
curr_sample/total_samples/curr_epoch = 1/300/1
Epoch 2
curr_sample/total_samples/curr_epoch = 1/300/2

3.  Set the correct number of samples within python train_pose.py 

4.  Train the model in a third terminal python train_pose.py

Step 1 to 3 has successfully done, But I ran into the following errors in step 4. 

2017-10-31 23:17:25.592649: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980, pci bus id: 0000:01:00.0)
Loaded VGG19 layer: block1_conv1
Loaded VGG19 layer: block1_conv2
Loaded VGG19 layer: block2_conv1
Loaded VGG19 layer: block2_conv2
Loaded VGG19 layer: block3_conv1
Loaded VGG19 layer: block3_conv2
Loaded VGG19 layer: block3_conv3
Loaded VGG19 layer: block3_conv4
Loaded VGG19 layer: block4_conv1
Loaded VGG19 layer: block4_conv2
Epoch 1/200000
Traceback (most recent call last):
  File "train_pose.py", line 174, in <module>
    initial_epoch=last_epoch
  File "/home/ros/anaconda3/envs/dl/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/ros/anaconda3/envs/dl/lib/python3.6/site-packages/keras/engine/training.py", line 2042, in fit_generator
    class_weight=class_weight)
  File "/home/ros/anaconda3/envs/dl/lib/python3.6/site-packages/keras/engine/training.py", line 1756, in train_on_batch
    check_batch_axis=True)
  File "/home/ros/anaconda3/envs/dl/lib/python3.6/site-packages/keras/engine/training.py", line 1378, in _standardize_user_data
    exception_prefix='input')
  File "/home/ros/anaconda3/envs/dl/lib/python3.6/site-packages/keras/engine/training.py", line 144, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking input: expected input_2 to have shape (None, None, None, 30) but got array with shape (10, 46, 46, 38)

Could you give some advice for the error?

**Comment by michalfaber** [comment]
@binliu-base Have you modified the model ? I see that the shapes don't match  (?, ?, ?, **30**) <=> (10, 46, 46, 38)

**Comment by binliu-base** [comment]
Figure out the problem, Yes I modified the model and set np_branch1 to 30.   Thanks for your fast response!  

Close the issue due to this is not a bug.
