### ISSUE TITLE
FileNotFoundError while running generate_masks.py

### ISSUE THREAD

**Issue by Yuren-Zhong** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#34]
while I run `python generate_masks.py`,
this is the output:

> 
python generate_masks.py
loading annotations into memory...
Traceback (most recent call last):
  File "generate_masks.py", line 17, in <module>
    coco = COCO(val_anno_path)
  File "/home/yurzho/anaconda3/envs/keras-openpose/lib/python3.6/site-packages/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/yurzho/keras_Realtime_Multi-Person_Pose_Estimation/dataset/annotations/person_keypoints_train2017.json'

>

**Comment by Yuren-Zhong** [comment]
forgot to unzip .zip files in annotations... : )
