### ISSUE TITLE
error running demo_image.py

### ISSUE THREAD

**Issue by GodsDusk** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#6]
Traceback (most recent call last):
  File "demo_image.py", line 248, in <module>
    canvas = process(input_image, params, model_params)
  File "demo_image.py", line 49, in process
    output_blobs = model.predict(input_img)
  File "/Users/env/lib/python2.7/site-packages/keras/engine/training.py", line 1695, in predict
    check_batch_axis=False)
  File "/Users/env/lib/python2.7/site-packages/keras/engine/training.py", line 111, in _standardize_input_data
    'Found: array with shape ' + str(data.shape))
ValueError: The model expects 3  arrays, but only received one array. Found: array with shape (1, 184, 200, 3)

**Comment by michalfaber** [comment]
it's fixed, thanks
