### ISSUE TITLE
Train_pose problem

### ISSUE THREAD

**Issue by jsh1204** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#84]
Hi, i'm poor at programming

so, i need some help please

i tried train_pose.py. but, it stoped at first epoch.

i ' don't know the reason. below is my terminal screen.

ubuntu 18 / python2.7  please help me

(tensorflow) sh@sh-WA50SCQ:~/Download/keras_Realtime_Multi-Person_Pose_Estimation-master$ python training/train_pose.py
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/pandas/_libs/__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/pandas/__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (hashtable as _hashtable,
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/pandas/core/dtypes/common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/pandas/core/util/hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import hashing, tslib
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/pandas/core/indexes/base.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, index as libindex, tslib as libts,
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/pandas/tseries/offsets.py:21: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.tslibs.offsets as liboffsets
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/pandas/core/ops.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as libalgos, ops as libops
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/pandas/core/indexes/interval.py:32: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs.interval import (
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/pandas/core/internals.py:14: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import internals as libinternals
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/pandas/core/sparse/array.py:33: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.sparse as splib
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/pandas/core/window.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.window as _window
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/pandas/core/groupby/groupby.py:68: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, reduction,
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/pandas/core/reshape/reshape.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as _algos, reshape as _reshape
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/pandas/io/parsers.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.parsers as parsers
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/pandas/io/pytables.py:50: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib, writers as libwriters
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/h5py/__init__.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._conv import register_converters as _register_converters
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/h5py/__init__.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/h5py/_hl/group.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .. import h5g, h5i, h5o, h5r, h5t, h5l, h5p
Using TensorFlow backend.
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _csparsetools
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:165: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/scipy/sparse/csgraph/_validation.py:5: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._tools import csgraph_to_dense, csgraph_from_dense,\
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:167: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._traversal import breadth_first_order, depth_first_order, \
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:169: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._min_spanning_tree import minimum_spanning_tree
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:170: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._reordering import reverse_cuthill_mckee, maximum_bipartite_matching, \
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/scipy/linalg/__init__.py:207: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ufuncs import *
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/scipy/interpolate/_bsplines.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _bspl
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ckdtree import *
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/scipy/spatial/__init__.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .qhull import *
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/scipy/spatial/distance.py:122: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hausdorff
/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/scipy/ndimage/measurements.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _ni_label
Loading vgg19 weights...
2018-08-15 22:56:35.701104: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-08-15 22:56:35.751795: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Loaded VGG19 layer: block1_conv1
Loaded VGG19 layer: block1_conv2
Loaded VGG19 layer: block2_conv1
Loaded VGG19 layer: block2_conv2
Loaded VGG19 layer: block3_conv1
Loaded VGG19 layer: block3_conv2
Loaded VGG19 layer: block3_conv3
Loaded VGG19 layer: block3_conv4
Loaded VGG19 layer: block4_conv1
Loaded VGG19 layer: block4_conv2
loading annotations into memory...
Done (t=10.77s)
creating index...
index created!
Loading image annot 0/118287
Loading image annot 5000/118287
Loading image annot 7000/118287
Loading image annot 8000/118287
Loading image annot 14000/118287
Loading image annot 15000/118287
Loading image annot 17000/118287
Loading image annot 19000/118287
Loading image annot 21000/118287
Loading image annot 23000/118287
Loading image annot 24000/118287
Loading image annot 25000/118287
Loading image annot 28000/118287
Loading image annot 31000/118287
Loading image annot 33000/118287
Loading image annot 35000/118287
Loading image annot 36000/118287
Loading image annot 38000/118287
Loading image annot 39000/118287
Loading image annot 40000/118287
Loading image annot 41000/118287
Loading image annot 42000/118287
Loading image annot 43000/118287
Loading image annot 47000/118287
Loading image annot 52000/118287
Loading image annot 53000/118287
Loading image annot 55000/118287
Loading image annot 56000/118287
Loading image annot 58000/118287
Loading image annot 60000/118287
Loading image annot 61000/118287
Loading image annot 64000/118287
Loading image annot 65000/118287
Loading image annot 68000/118287
Loading image annot 71000/118287
Loading image annot 72000/118287
Loading image annot 73000/118287
Loading image annot 78000/118287
Loading image annot 79000/118287
Loading image annot 82000/118287
Loading image annot 85000/118287
Loading image annot 88000/118287
Loading image annot 91000/118287
Loading image annot 92000/118287
Loading image annot 97000/118287
Loading image annot 103000/118287
Loading image annot 106000/118287
Loading image annot 108000/118287
Loading image annot 110000/118287
Loading image annot 111000/118287
Loading image annot 113000/118287
Loading image annot 114000/118287
Loading image annot 115000/118287
Loading image annot 117000/118287
[0815 22:57:17 @parallel.py:291] [PrefetchDataZMQ] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
Process _Worker-1:
Traceback (most recent call last):
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/tensorpack/dataflow/parallel.py", line 267, in run
    for dp in self.ds.get_data():
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/tensorpack/dataflow/common.py", line 274, in get_data
    for dp in self.ds.get_data():
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/tensorpack/dataflow/common.py", line 274, in get_data
    for dp in self.ds.get_data():
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/tensorpack/dataflow/common.py", line 275, in get_data
    ret = self.func(copy(dp))  # shallow copy the list
  File "training/../training/dataset.py", line 96, in augment
    scale=meta.scale))
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/tensorpack/dataflow/imgaug/base.py", line 48, in augment_return_params
    return self._augment_return_params(d)
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/tensorpack/dataflow/imgaug/base.py", line 54, in _augment_return_params
    prms = self._get_augment_params(d)
  File "training/../training/augmentors.py", line 226, in _get_augment_params
    scale_abs = self.target_dist / scale
ZeroDivisionError: float division by zero
Process _Worker-3:
Traceback (most recent call last):
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/tensorpack/dataflow/parallel.py", line 267, in run
    for dp in self.ds.get_data():
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/tensorpack/dataflow/common.py", line 274, in get_data
    for dp in self.ds.get_data():
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/tensorpack/dataflow/common.py", line 274, in get_data
    for dp in self.ds.get_data():
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/tensorpack/dataflow/common.py", line 275, in get_data
    ret = self.func(copy(dp))  # shallow copy the list
  File "training/../training/dataset.py", line 96, in augment
    scale=meta.scale))
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/tensorpack/dataflow/imgaug/base.py", line 48, in augment_return_params
    return self._augment_return_params(d)
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/tensorpack/dataflow/imgaug/base.py", line 54, in _augment_return_params
    prms = self._get_augment_params(d)
  File "training/../training/augmentors.py", line 226, in _get_augment_params
    scale_abs = self.target_dist / scale
ZeroDivisionError: float division by zero
Epoch 1/200000
2018-08-15 22:58:28.281299: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at mkl_concat_op.cc:816 : Aborted: Operation received an exception:Status: 3, message: could not create a reorder primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:813
Traceback (most recent call last):
  File "training/train_pose.py", line 237, in <module>
    initial_epoch=last_epoch)
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/keras/engine/training_generator.py", line 213, in fit_generator
    class_weight=class_weight)
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 1215, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2666, in __call__
    return self._call(inputs)
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2636, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1454, in __call__
    self._session._session, self._handle, args, status, None)
  File "/home/sh/.conda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 3, message: could not create a reorder primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:813
	 [[Node: concatenate_1/concat = _MklConcatV2[N=3, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](Mconv5_stage1_L1/BiasAdd, Mconv5_stage1_L2/BiasAdd, activation_12/Relu, training/MultiSGD/gradients/concatenate_1/concat_grad/mod, Mconv5_stage1_L1/BiasAdd:2, Mconv5_stage1_L2/BiasAdd:2, activation_12/Relu:1, DMT/_45)]]
PrefetchDataZMQ successfully cleaned-up.
PrefetchDataZMQ successfully cleaned-up.

**Comment by sungwonida** [comment]
Try Python 3 (maybe 3.5+ if not 3.0).
Please refer to my requirements below. (Use tensorflow-gpu if you want)
And I definitely recommand using virtualenv or conda for sandboxing the environments if you don't want to mess the things.

absl-py==0.2.2
astor==0.7.1
backcall==0.1.0
configobj==5.0.6
cycler==0.10.0
decorator==4.3.0
gast==0.2.0
grpcio==1.13.0
h5py==2.8.0
ipykernel==4.8.2
ipython==6.4.0
ipython-genutils==0.2.0
jedi==0.12.1
jupyter-client==5.2.3
jupyter-core==4.4.0
Keras==2.2.0
Keras-Applications==1.0.2
Keras-Preprocessing==1.0.1
kiwisolver==1.0.1
Markdown==2.6.11
matplotlib==2.2.2
numpy==1.14.5
opencv-python==3.4.1.15
pandas==0.23.3
parso==0.3.1
pexpect==4.6.0
pickleshare==0.7.4
Pillow==5.2.0
prompt-toolkit==1.0.15
protobuf==3.6.0
ptyprocess==0.6.0
pyarrow==0.9.0
pycocotools==2.0.0
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.7.3
pytz==2018.5
PyYAML==3.13
pyzmq==17.1.0
scipy==1.1.0
simplegeneric==0.8.1
six==1.11.0
tabulate==0.8.2
tensorboard==1.9.0
tensorflow==1.9.0
tensorpack==0.8.6
termcolor==1.1.0
tornado==5.1
tqdm==4.23.4
traitlets==4.3.2
wcwidth==0.1.7
Werkzeug==0.14.1
