### ISSUE TITLE
data load error during training time

### ISSUE THREAD

**Issue by jzwang123** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#95]
Did someone also get the following error during data load? Thanks!

Process _Worker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jiazhuo/tensorflow/venv/local/lib/python2.7/site-packages/tensorpack/dataflow/parallel.py", line 270, in run
    socket.send(dumps(dp), copy=False)
  File "/home/jiazhuo/tensorflow/venv/local/lib/python2.7/site-packages/tensorpack/utils/serialize.py", line 17, in dumps_msgpack
    return msgpack.dumps(obj, use_bin_type=True)
  File "/home/jiazhuo/tensorflow/venv/local/lib/python2.7/site-packages/msgpack_numpy.py", line 165, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 284, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 290, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 287, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 263, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 281, in msgpack._packer.Packer._pack
TypeError: can't serialize <read-write buffer for 0x7f9328a582b0, size 196608, offset 0 at 0x7f932c6d6730>

**Comment by chenyanyin** [comment]
do you have deal with it?
